### ISSUE TITLE
that was fast

### ISSUE THREAD

**Issue by koaning** [bmewing/requirements#1]
but i wonder. whats the benefit of having this if you've already got packrat?

**Comment by bmewing** [comment]
Twofold, in my opinion.
1. Project initialization. Packrat covers what you install today. This would let you lock in, for example, dplyr at version 0.7.0 so you don't have to worry about Hadley making random changes. And you can add it to a new project by just copying the text file.
2. Readability. The packrat lockfile isn't very readable, this is a typical standard that lots of people are used to.
