### ISSUE TITLE
CLI?

### ISSUE THREAD

**Issue by AdamSpannbauer** [bmewing/requirements#11]
Not sure how much value this adds, but it could be slick to have an interface where something like the below workflow is possible from the command line.

```bash
git clone project-using-r-requirements.txt-file.git
install_requirements --packrat
```

Could be convenient for devops type applications where running a shell script to pull requirements is more useful than running R code.  Of course, this task could be done with `Rscript -e 'requirements::requirements(load=FALSE)'`, but not as sexy.  I've never actually tried to bundle an R script like this though so not sure the effort to value ratio.

**Comment by bmewing** [comment]
Found this question on SO and Dirk's answer suggests that maybe this isn't possible. https://stackoverflow.com/a/13434754/2890590

**Comment by AdamSpannbauer** [comment]
yeah and I had 2nd thoughts about usefulness.  You'd still have to somehow install the `requirements` package before doing the cli requirements install.
