### ISSUE TITLE
add requirements.txt for this project

### ISSUE THREAD

**Issue by AdamSpannbauer** [bmewing/requirements#12]
Definitely, need to add a `requirements.txt` for this project to dogfood etc

**Comment by bmewing** [comment]
There's one in the example folder, but do you mean a requirements.txt for the dependencies in the package?

**Comment by AdamSpannbauer** [comment]
See #13 for what I was thinking. I guess this would supersede the `examples/requirements.txt`?  I like the idea of practicing what the package preaches though by including a real requirements file for the package.

It did bring up the issue of needing to add `requirements.txt` to the `.Rbuildignore`.  Should this be something built into `generate_requirements()`?

FYI the requirements file was generated with the below command.

```r
requirements::generate_requirements('R/*.R')
```

**Comment by bmewing** [comment]
I think `examples/requirements.txt` is still needed since the official one won't be bundled with the R package, right?

**Comment by AdamSpannbauer** [comment]
the `examples` dir is currently in the `.Rbuildignore` due to causing a note on package check.  CRAN is pretty picky about even the notes, i think the only way to bundle one would be via vignette, but even that wouldnt be a real example of an actual txt file

**Comment by bmewing** [comment]
fair point, the repo will always show it and we can have a vignette that describes usage
