### ISSUE TITLE
more descriptive error message for file.exists check?

### ISSUE THREAD

**Issue by AdamSpannbauer** [bmewing/requirements#14]
I ran into the following:

```
> requirements('requirements.txt')
Error in requirements("requirements.txt") : file.exists(req) is not TRUE
```

Definitely preventable by reading the docs ~better~ at all, but if the error told me that `"requirements.txt/requirements.txt"` didn't exist it would've been more obvious what went wrong.

It would take away the convenience of the `stopifnot` call, but since `req` is not visible to the user w/o viewing source code I think a custom check + `stop` + custom error message showing the exact path checked by `file.exists` might be more user-friendly.

If you agree then I think the `stopifnot(length(content) > 0)` check is along the same lines.

**Comment by bmewing** [comment]
Agree, this should be done before first release

**Comment by bmewing** [comment]
related to this, should the package require that you name the file 'requirements.txt' or should the user be able to point to a specific file?

**Comment by AdamSpannbauer** [comment]
I lean towards freedom to name it whatever you want. The default can be `file.path(getwd(), 'requirements.txt')`, but maybe there could be some reason(s) a user needs/wants the freedom to name it whatever.  (i.e. some Frankenstein project with python and r components and requirements files for both)

**Comment by bmewing** [comment]
I'm pretty sure this has all been addressed in other PRs already.
