### ISSUE TITLE
Archive doesn't get non-updated package versions

### ISSUE THREAD

**Issue by bmewing** [bmewing/requirements#19]
The method being used to fetch package versions doesn't seem to include packages that have never been updated (readOffice is an example).

**Comment by bmewing** [comment]
Scratch that, it doesn't include the latest version of any package...

**Comment by AdamSpannbauer** [comment]
Happy to help debug, but I'm not sure I understand the issue.  What specifically is happening and what is expected?

**Comment by bmewing** [comment]
addressed with #28
