### ISSUE TITLE
Use `==` instead of `=`?

### ISSUE THREAD

**Issue by AdamSpannbauer** [bmewing/requirements#2]
Given that the `requirements.txt` idea seems pretty tightly modeled after the Python counterpart.  Do you think that `==` would be preferable to `=` (as show in README example)?  This is how it is done in in a Python project's `requirements.txt`.

References:
* ['Requirements files' from `pip`'s documentation](https://pip.readthedocs.io/en/1.1/requirements.html)
* [Full list of 'Version specifiers' from PEP 440](https://www.python.org/dev/peps/pep-0440/#version-specifiers)

**Comment by bmewing** [comment]
I'd like to bring this in line with PEP standards, so thanks for the links.
