### ISSUE TITLE
add linting to dev machines/CI

### ISSUE THREAD

**Issue by AdamSpannbauer** [bmewing/requirements#24]
\<insert well-established arguments for code linting\>

(and i want to experiment with this feature of `lintr` and figured this is a good place to try)

**Comment by AdamSpannbauer** [comment]
Proposed `.lintr` cofiguration

```
linters: with_defaults(line_length_linter = line_length_linter(120), assignment_linter = NULL)
```

* ~Align with PEP 8 line length of 120 characters~ Turns out pep 8 is 80. I just assumed 120 cause that’s what pycharm enforces by default. Open to lower to 80. 
* Ignore linting that forces usage of `<-` for assignment

----

See https://github.com/bmewing/requirements/commit/7199901d155966c52638bfceb86af774c0dce96a for example output from lintr bot ~disliking~ suggesting improvements to our code.

Holding off on fixing issues to avoid conflicts.

**Comment by AdamSpannbauer** [comment]
Additionally experimenting with adding `lintr` as a pre-commit hook.

The below script when added locally as `.git/hooks/pre-commit` will reject commits that fail linting.  I'm going to be using it locally to preempt larger issues appearing in CI.  It might seem paranoid to have this and the CI lint, but I like the strictness of it all.

```
# Run lint_package, print results, use number of lint issues as exit status
Rscript -e '(lint_issues = lintr::lint_package()); quit(save = "no", status = length(lint_issues))'

# Exit with status of Rscript (non-zero will reject commit)
exit $?
```

**Comment by AdamSpannbauer** [comment]
~Additionally, there is the [~`goodpractice`~](https://github.com/MangoTheCat/goodpractice) package that can check code for complexity (i.e. it does codeclimate style checks).  Testing locally now.~

A subset of the `goodpractice` functionality is the [`cyclocomp`](https://github.com/MangoTheCat/cyclocomp) package which checks for complexity.  This seems to provide more value to us rather than the full `goodpractice` capability.

Output of running `cyclocomp::cyclocomp_package_dir()` on `requirements` can be seen below.  

According to resources like codeclimate we should strive for `(cyclomatic complexity) < 5`.  We can decide on where we want to be on this. 

```
                            name cyclocomp
6            compare_and_install        17
1     append_version_requirement         3
7                compare_version         3
9                  load_packages         3
10             load_requirements         3
3          check_extreme_version         2
4           check_newest_version         2
5           check_oldest_version         2
17          safe_package_version         2
2    append_version_requirements         1
8          generate_requirements         1
11                 match_package         1
12                match_packages         1
13                   PACKAGE_RES         1
14                  read_archive         1
15  read_package_lines_from_file         1
16 read_package_lines_from_files         1
18               validate_eq_sym         1
19       write_requirements_file         1
```

**Comment by bmewing** [comment]
> Additionally experimenting with adding `lintr` as a pre-commit hook.
> 
> The below script when added locally as `.git/hooks/pre-commit` will reject commits that fail linting. I'm going to be using it locally to preempt larger issues appearing in CI. It might seem paranoid to have this and the CI lint, but I like the strictness of it all.
> 
> ```
> # Run lint_package, print results, use number of lint issues as exit status
> Rscript -e '(lint_issues = lintr::lint_package()); quit(save = "no", status = length(lint_issues))'
> 
> # Exit with status of Rscript (non-zero will reject commit)
> exit $?
> ```

Is this a .sh file that goes there? I've never used pre-commit hooks

**Comment by bmewing** [comment]
Related to the code complexity, we can simply compare_version to be <<5 by making a few changes. This gets rid of two if/else blocks. I don't want to make the change until some of the other code has flowed in, but wanted to note it here.

```
if(existing == '*' | target == '*'){
    return(comp != "!=")
}
`~=` <- `==`
return(get(comp)(existing, target))
```

**Comment by AdamSpannbauer** [comment]
It's a file with no extension named `pre-commit` in `requirements/.git/hooks`.  It will execute every time `git commit` is called and fail the commit if the exit status != 0.

(I currently have mine commented out until we get around to some boring house-keeping code reformatting)

**Comment by bmewing** [comment]
So, do you think with lintr-bot being fixed in CI that we're ready to add the pre-hook and close this issue @AdamSpannbauer ?

**Comment by AdamSpannbauer** [comment]
I'm good with closing and I figure that the pre-commit hook can be an optional additional strict option.  Since we can't standardize commit hooks by storing them in the repo I don't feel too strongly about them.

Now that lintr-bot is working well I think we can let it tell us about lint issues.  A possibly more worthwhile hook is R CMD check/devtools::check, but this could be slow (and again i think can just be a personal decision)

**Comment by AdamSpannbauer** [comment]
lintr-bot had its first useful feedback!!  I'm so proud I'm closing this issue.

![image](https://user-images.githubusercontent.com/16326083/55367791-bb089f00-54bc-11e9-99ef-b60c66ce3348.png)
