### ISSUE TITLE
investigate metacran db for version fetching

### ISSUE THREAD

**Issue by AdamSpannbauer** [bmewing/requirements#26]
* [crandb project page](https://github.com/metacran/crandb)
* [anchor to relevant documentation](https://github.com/metacran/crandb#the-raw-api)

**Comment by AdamSpannbauer** [comment]
needs to replicate input/output of `get_available_versions()`

**Comment by AdamSpannbauer** [comment]
possible new implementation in PR #28.  This would drop the `repo` argument from the function.

**Comment by bmewing** [comment]
@AdamSpannbauer has this been full addressed since we merged #28?

**Comment by AdamSpannbauer** [comment]
yes sir
