### ISSUE TITLE
simplify install_requirements default args

### ISSUE THREAD

**Issue by AdamSpannbauer** [bmewing/requirements#27]
Current args and defaults:

> ```r
> install_requirements <- function(requirements = file.path(getwd(),"requirements.txt"),
>                                  packrat = FALSE, dryrun = FALSE,
>                                  verbose = dryrun, repo = options()$repo[1],
>                                  gen = !file.exists(requirements),
>                                  glob_paths = file.path(dirname(requirements),"*.R"), ...) {
> ```

Proposal to change to: 
```diff
- install_requirements <- function(requirements = file.path(getwd(),"requirements.txt"),
+ install_requirements <- function(requirements = "requirements.txt",
                                 packrat = FALSE, dryrun = FALSE,
                                 verbose = dryrun, repo = options()$repo[1],
                                 gen = !file.exists(requirements),
-                                glob_paths = file.path(dirname(requirements),"*.R")
+                                glob_paths = "*.R", ...) {
```

* `file.path(getwd(),"requirements.txt")` is equivalent to `"requirements.txt"`
* Assuming default `requirements` then `file.path(dirname(requirements),"*.R")` is equivalent to `"*.R"`.  This assumption breaks if `requirements` is specified in a different dir.  I'm not totally sold on this one being changed, but I think I prefer the simplicity and leave it to the user if they're overriding defaults.

**Comment by bmewing** [comment]
I agree on the first point, it's entirely redundant to do getwd(). I do think the added complexity in glob_paths does allow for the user to have a more complex setup and have it handled automatically, so for now I'd vote to accept the first point and drop the second.
