### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by AdamSpannbauer** [bmewing/requirements#29]
brainstorm logo and slap it on a sexy-hexy sticker format to appear in readme/docs/etc

**Comment by AdamSpannbauer** [comment]
potential concept (source: first idea that popped into my head + keynote as photo-editor)

<p align='center'>
  <img width='25%' src=https://user-images.githubusercontent.com/16326083/55281374-e8611b80-5309-11e9-98fb-67f75162ce3d.png>
</p>

**Comment by bmewing** [comment]
The $15 + editing it in Illustrator version

<p align='center'>
  <img width='25%' src="https://user-images.githubusercontent.com/16339866/56537916-b40b0480-652f-11e9-8062-73f2a72a6109.png">
</p>

**Comment by AdamSpannbauer** [comment]
really like this btw, to get it on the public record.  Looks nice on hex and the checkmark by itself would look good as a favicon for the pkgdown site

**Comment by AdamSpannbauer** [comment]
Putting this in the public record.

If we do change function naming conventions to `rip` (to mirror `pip` and stand for "`requirements` installs packages"), then I vote to fully embrace the imagery/branding we can use with the word rip.  Below is my IRL mock-up of a potential design using "rip" as a component of the logo design.

Since you footed bill for first Fiverr logo I'd be more than happy to fund a pass at logo-ifying this idea or a different one you might have in mind that incorporates rip.  Thoughts? Select opinion below.

* [ ] I like "rip" but dislike the below idea
* [ ] I like "rip" and the below idea
* [x] I dislike this idea entirely, why would you even bring it up? I would like to keep the current logo and part ways as open source collaborators
* [ ] Other

<p  align="center">
<img src=https://user-images.githubusercontent.com/16326083/56755445-8c997f00-675d-11e9-9ae6-293c10ce0b2f.png width=50%>
</p>

**Comment by bmewing** [comment]
My main concern with this image specifically is that it suggests to me we're destroying the requirements rather than establishing them.

**Comment by AdamSpannbauer** [comment]
semi-closed issue. hex logo added to readme in #90 (not sure when considered closed)
