### ISSUE TITLE
use getParseData for read_package_lines_from_file

### ISSUE THREAD

**Issue by AdamSpannbauer** [bmewing/requirements#46]
`read_package_lines_from_file()` and `match_package()` currently use string matching to accomplish the goal of finding lines in an R script that load/reference a package (`read_package_lines_from_file()`) and subsequently extracting the package names (`match_package()`).

A solution using `getParseData` could be more comprehensive and simpler.

Filter to lines containing `SYMBOL_PACKAGE` or `SYMBOL_FUNCTION_CALL` + one of the `library()`-like functions.

```r
> getParseData(parse(text='library(testthat); testthat::test_that()'))
   line1 col1 line2 col2 id parent                token terminal      text
9      1    1     1   17  9      0                 expr    FALSE          
1      1    1     1    7  1      3 SYMBOL_FUNCTION_CALL     TRUE   library
3      1    1     1    7  3      9                 expr    FALSE          
2      1    8     1    8  2      9                  '('     TRUE         (
4      1    9     1   16  4      6               SYMBOL     TRUE  testthat
6      1    9     1   16  6      9                 expr    FALSE          
5      1   17     1   17  5      9                  ')'     TRUE         )
10     1   18     1   18 10      0                  ';'     TRUE         ;
20     1   20     1   40 20      0                 expr    FALSE          
16     1   20     1   38 16     20                 expr    FALSE          
13     1   20     1   27 13     16       SYMBOL_PACKAGE     TRUE  testthat
14     1   28     1   29 14     16               NS_GET     TRUE        ::
15     1   30     1   38 15     16 SYMBOL_FUNCTION_CALL     TRUE test_that
17     1   39     1   39 17     20                  '('     TRUE         (
18     1   40     1   40 18     20                  ')'     TRUE         )
```

**Comment by bmewing** [comment]
Doesn't that still leave string matching to get the `library()` like functions?

**Comment by AdamSpannbauer** [comment]
Yeah, I think string matching will still be needed for example to get `data.table` from `library(data.table)` or `library("data.table")` (unless some other fancy base R function pops up in research).  

Using the parse data will avoid mishandling the edge case of something like: `my_string = "library(data.table)"` being included.  More likely edge case example would be a string with `::`.

New process could look like:

* get parse data
* pull the `text` of `SYMBOL_PACKAGE` rows as extracted packages
* pull line numbers from `SYMBOL_FUNCTION_CALL` rows where `text` is in ['library', 'require', 'p_load']
* use these lines as input to current string matching done in `match_package()`

**Comment by bmewing** [comment]
Performance of the proposed solution was pretty bad
