### ISSUE TITLE
gen_requirements from packrat lockfile?

### ISSUE THREAD

**Issue by bmewing** [bmewing/requirements#57]
If a project is already using packrat, would it make sense to have a routine that extracts package requirements from the lockfile? Or would that be too many requirements?

**Comment by AdamSpannbauer** [comment]
I feel like I'd have to discuss with you to understand packrat better (im not too familiar).

For example, does packrat specifically look for what packages are used in a project or does it just look for what packages are installed in the environment?

**Comment by AdamSpannbauer** [comment]
What would the ideal workflow for this be?

A dedicated function (maybe `generate_from_lock` for example) or for `generate_requirements()` to determine the user pointed it at a lock file?  Or something else entirely?

In the current format, you can't generate requirements for both `.lock` & `.R` files.  One design option would be to have an `append` style argument to where dependencies could be iteratively added to the same `requirements.txt`.

I don't think the actual act of parsing the lock file will be difficult, but I think the most crucial part is how the API incorporates this addition.

**Comment by bmewing** [comment]
IMO there would be an exported function `generate_from_packrat` and it
would have an optional `append` argument. Then, `generate_requirements`
would have an optional lockfile argument that, if populated would read and
append the lockfile to the other requirements. That way users can call just
one if they know what they need or can call the more general function and
get both.

**Comment by AdamSpannbauer** [comment]
First pass for reading from lockfile in https://github.com/bmewing/requirements/commit/79b03b2a4b5684a09aed28517e5f9ea1159a4df9 (untested 😢)

If a package is listed in the lockfile, is it guaranteed to have a version listed for it?  Right now I have the logic written assuming this is the case (because it's simpler to assume this).  If this isn't a guarantee this can be revised to handle the exception.

**Comment by bmewing** [comment]
My understanding is the version is always included.

**Comment by AdamSpannbauer** [comment]
Just pushed a first pass implementation of the functions discussed.  On this first pass, I named the function `packrat_to_requirements()` to try and be descriptive without being overly verbose.  Open to changing the name, but this was the best I could come up with as of now.

Tests still need to be written to cover what was pushed in the most recent commits.

**Comment by bmewing** [comment]
Where did you push it to? Is it the lockfile_#57?

**Comment by AdamSpannbauer** [comment]
Yep. Was gonna finish up tests then open up PR. I don’t have the steam to do it tonight, but if you have momentum and are wanting to keep going feel free to it take over.

**Comment by AdamSpannbauer** [comment]
Closed by merging #71
