### ISSUE TITLE
Sanitize requirement file content

### ISSUE THREAD

**Issue by AdamSpannbauer** [bmewing/requirements#72]
2 part issue but felt related enough to keep in one place.

## Blank Lines

I was running through testing the edge case of conflicting requirement specification and came across a bug where a blank line in a requirements file will cause `process_requirements_file()` to throw an error.

```r
> req = "/tmp/req.txt"
> write_requirements_file(c("data.table >= 1.0.0", "data.table == 1.12.0"),
                          file_path =req)
> (content = read_requirements_file(req))
[1] "# Generated by requirements::generate_requirements().  Modify as needed."
[2] "# Install using requirements::install_requirements()."                   
[3] ""                                                                        
[4] "data.table >= 1.0.0"                                                     
[5] "data.table == 1.12.0"                                        
> (content = remove_comments_from_req(content))
[1] ""                     "data.table >= 1.0.0"  "data.table == 1.12.0"
```

This blank line causes the below check to throw the below error

```r
if (length(content) > 0) {
  stop(sprintf(REQ_FILE_RESOLUTION_ERR, paste(content, collapse = ", ")))
}
```

> ```
> Error: Not all requirements are allowed: 
> ```

## Conflicting req specification

From what I can tell there doesn't seem to be protection against conflicting requirements.  Below shows how `pip` handles this (created requirements file using: `write_requirements_file(c("vidstab == 1.5.6", "vidstab == 1.5.5"), file_path = '/tmp/req.txt')`)

```
$ pip install -r /tmp/req.txt
Double requirement given: vidstab==1.5.5 (from -r /tmp/req.txt (line 5)) (already in vidstab==1.5.6 (from -r /tmp/req.txt(line 4)), name='vidstab')
```

**Comment by bmewing** [comment]
It looks like pip ignores blank lines (we should too)

**Comment by bmewing** [comment]
I checked a triple specification where the first two are not necessarily mutually exclusive. It still only reports 'double requirement given'

```
vidstab > 1.5
vidstab < 1.6
vidstab >= 1.6
```

**Comment by AdamSpannbauer** [comment]
Definitely simpler to just fail on any duplicated requirement specification.  However, it might be a nice feature down the line to handle valid duplicated requirements (i.e. you're first 2 lines you listed)?  (unless you see an easy path forward to handle, and want to go ahead and tackle it).  It's not high value add but there could be an instance of a project needing functionality from a version range that has a span greater than what `~=` provides (IMO the user should just use `==` or `~=` and restrict their range if this is the case, but maybe there's an argument against this).

I think it would be a nice improvement to point out all duplicated lines in our error vs pip's.  For example, to include references to every requirement of your test file above.  They likely process differently and throw an error at first instance of duplication; the way our requirements are currently being read we already have all the info to report all dups.

**Comment by bmewing** [comment]
I was curious if duplication extended beyond pypi installs. So I tried the two below. The first one is a valid git+ install, same repo just two different tags. It doesn't fail and tries to download/install both.
```
git+https://github.com/bmewing/mgsub-python@master
git+https://github.com/bmewing/mgsub-python@v1.0
```
Second case is two local files, same except for different version numbers, it ignores it and tries to install the (non-existent) local file
```
./downloads/numpy-1.9.2-cp34-none-win32.whl
./downloads/numpy-1.9.3-cp34-none-win32.whl
```

**Comment by bmewing** [comment]
Also the following doesn't throw any errors
```
mgsub
mgsub
```

**Comment by bmewing** [comment]
So, I'm thinking we remove duplicates first, then take lines which begin with a legal r package and check for duplicates

**Comment by AdamSpannbauer** [comment]
Implementation wise it’s easy to ignore pure dups like that mgsub example.  I like being strict from a design standpoint, but open to your judgement of situation.
