### ISSUE TITLE
Protect against duplicated reqs in generate helpers

### ISSUE THREAD

**Issue by AdamSpannbauer** [bmewing/requirements#73]
Related to #72

The current process of `generate_requirements()` will *always* result in duplicated requirements if generating from discovered packages + packrat.lock.  This would lead to a requirements.txt written entirely by the package failing the package's install process (once #72 is addressed)

The removal of duplicated requirements should be handled before writing to file.

I think fixing this is only worthwhile in the case of `generate_requirements()` + packrat.lock option.  If otherwise generating requirements from packrat.lock and using `append = TRUE` then parsing the existing requirements to check for duplication seems like it should be out of scope and left to the user to handle.

**Comment by bmewing** [comment]
Addressed with #84
