### ISSUE TITLE
Ignore packages found in comments when generating reqs

### ISSUE THREAD

**Issue by AdamSpannbauer** [bmewing/requirements#77]
Unless #58 is resolved, an easy step to improve the regex-based package matching would be the removal of comments from candidate lines.  This should be able to leverage the `remove_comments_from_req()` helper that's already being used on the install side of things.

L O W H A N G I N G F R U I T 🍎 🍌 🍇

**Comment by bmewing** [comment]
`remove_comments_from_req()` might be a little too specific depending on what you're thinking, what exactly are you wanting to do? Maybe just a refactor with `remove_comments_from_req()` will do the trick.

**Comment by AdamSpannbauer** [comment]
Yep, looking at the actual logic in the function you're right; `remove_comments_from_req()` is doing more than I thought.

The functionality needed to close this issue is limited to removing comments from a character vector (full line comments and inline).

**Comment by AdamSpannbauer** [comment]
merging #79 will make this task very simple.

a call to `remove_comments_from_req()` to rm comments needs to be added to `read_package_lines_from_file()` (and appropriate testing added)
