### ISSUE TITLE
freeze wrapper of gen req function to mimic PIP naming

### ISSUE THREAD

**Issue by AdamSpannbauer** [bmewing/requirements#85]
`generate_requirements()` is essentially `pip freeze > requirements.txt`

To make this more obvious to python users coming to this package a wrapper of `generate_requirements()` should be made that includes "freeze" in the name.  We discussed offline to keep `generate_requirements()` as well since this naming might be more user-friendly to a pure R user who has never used `pip freeze`

**Comment by bmewing** [comment]
Closed in #87
